; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro8MHzatmega328]
platform = atmelavr
board = pro8MHzatmega328
; No framework line here = Pure AVR-GCC

; Ensure the code knows it is running at 8MHz
board_build.f_cpu = 8000000L

; --- UART Upload Settings ---
upload_protocol = arduino
; Replace with your actual port (Run 'ls /dev/cu.*' in terminal to find it)
upload_port = /dev/cu.usbserial-D308HLRH 
; Standard for 8MHz bootloaders is 57600. If that fails, try 19200.
upload_speed = 57600

; This forces the serial monitor to match your chip's speed
monitor_speed = 9600

; If you have multiple devices plugged in, tell it exactly which one to watch
; Replace with your actual port from 'ls /dev/cu.usb*'
monitor_port = /dev/cu.usbserial-D308HLRH
