# AVR LED Mode Controller

Project intended to test implementation of a timer driving LEDs within a low power mode along with toggle switch driven interrupt that modifies the timer behavior.

## 📂 Repository Structure

The following are included in the repo to allow for working implementation and testing within the Wokwi simulator:

| File | Description |
| :--- | :--- |
| **`main.c`** | The primary source file containing the implementation.
| **`main.elf`** | The Executable and Linkable Format file generated by the AVR-GCC toolchain. |
| **`main.hex`** | The file containing the machine code ready to be loaded into the MCU. |
| **`diagram.json`** | The Wokwi hardware configuration file for simulation. |
| **`wokwi.toml`** | The simulator configuration file that links the virtual hardware to the `main.elf` artifact. |
| **`README.md`** | Project documentation and build instructions.

## 🛠 Build Instructions

### Prerequisites
* **AVR-GCC Toolchain:** Required to compile the C source into machine code.
* **avr-libc:** Standard library for AVR microcontrollers.
* **Wokwi VSCode Extension:** For hardware simulation.

### Compilation Commands
Navigate to the project root and execute the following commands in your terminal:

1. **Compile the source:**
   ```bash
   avr-gcc -mmcu=atmega328p -DF_CPU=16000000UL -Os -Wall main.c -o main.elf